# 딥러닝 시작하기!

### 교재 : Deep Learning from scratch 밑바닥부터 시작하는 딥러닝

오늘의 챕터 1 ~ 3 단원

## Chap 1. 간단히 numpy

numpy는 파이썬의 자료형 list보다 좀 더 편리하게 행렬 연산을 할 수 있게 해주는

매우 좋은 파이썬 외부 라이브러리 입니다.

넘파이를 쓰기위해서 numpy를 깔고 import를 해줘야합니다.


In [4]:
import numpy as np

### 넘파이 배열 생성하기 

np.array() 메소드로 넘파이 배열을 만들 수 있습니다.

In [37]:
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [38]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [39]:
type(x)

numpy.ndarray

In [40]:
x.dtype

dtype('float64')

### 2 x 2 행렬 만들기

In [27]:
A = np.array([[1,2],[3,4]])

B = np.array([[4,5],[6,7]])

In [29]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


#### 행렬의 모양 알아보기 
 ( 행 , 열)

In [30]:
A.shape

(2, 2)

In [36]:
A.dtype

dtype('int64')

### 행렬 사칙연산

우리가 고등학교 때 배운 그 행렬 사칙연산 맞습니다...!

아시죠...?ㅎㅎ

In [41]:
A * B

array([[ 4, 10],
       [18, 28]])

In [42]:
A + B

array([[ 5,  7],
       [ 9, 11]])

In [43]:
A - B

array([[-3, -3],
       [-3, -3]])

In [44]:
A / B

array([[ 0.25      ,  0.4       ],
       [ 0.5       ,  0.57142857]])

#### 선행대수학 공부하고 싶은 사람은 아래 링크로!

ps. 딥러닝하려면 행렬 연산이랑 벡터 미분을 할 줄 알아야 합니다...ㅠ

파이썬으로 선형대수학 하기: [https://www.slideshare.net/ssuser7e10e4/linear-algrbra](https://www.slideshare.net/ssuser7e10e4/linear-algrbra)

파이썬으로 행렬(벡터) 미분하기: [https://www.slideshare.net/ssuser7e10e4/matrix-calculus](https://www.slideshare.net/ssuser7e10e4/matrix-calculus)


### Chap 2. 퍼셉트론

#### 갑자기 퍼셉트론은 왜 나오는거지..?

- 퍼셉트론은 신경망(딥러닝)의 기원이 되는 알고리즘 이기 때문..!
- 퍼셉트론의 구조를 배우는 것은 신경망과 딥러닝을 배우는데 중요한 아이디어가 된다!

#### 그래서 퍼셉트론은 뭔가?

- 퍼셉트론은 다수의 신호를 입력받아서 하나의 신호로 출력하는 것
- 여기서 신호란 강물처럼 흐름이 있는 것을 생각하면 된다
- 퍼셉트론은 신호를 받아서 흐름을 만들고 그 정보를 앞으로 전달한다.

#### 실제 전류와 다른점

- 신호가 흐른다(1) 안흐른다(0) 두가지의 값을 가진다

![퍼셉트론](./img/perceptron.png)

### 신경망( neural network) 시작하기

#### 그럼 퍼셉트론에서 신경망은 뭐가 다른가?!

신경망에서 활성화 함수( activation function)가 도입된다.

![신경망](./img/activation.png)

### 신경망(neural network) 연산은 행렬 곱 연산과 같습니다..

신경망을 이해하기 위해